---
- hosts: web-host1
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=latest
  - name: replace default index.html file
    copy: src=/etc/ansible/playbook/index.html dest=/var/www/html/ mode=0644
    notify:
    - restart apache2
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted